//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSRevitAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoWarningSuppress {
            get {
                return ((bool)(this["AutoWarningSuppress"]));
            }
            set {
                this["AutoWarningSuppress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 20")]
        public global::System.Drawing.Point TagToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["TagToolbarLocation"]));
            }
            set {
                this["TagToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not assigned")]
        public string PartsManagerLocation {
            get {
                return ((string)(this["PartsManagerLocation"]));
            }
            set {
                this["PartsManagerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenOrig {
            get {
                return ((bool)(this["OpenOrig"]));
            }
            set {
                this["OpenOrig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenNew {
            get {
                return ((bool)(this["OpenNew"]));
            }
            set {
                this["OpenNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnitLines {
            get {
                return ((bool)(this["UnitLines"]));
            }
            set {
                this["UnitLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Point DimNotFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["DimNotFormLocation"]));
            }
            set {
                this["DimNotFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Size BBFormSize {
            get {
                return ((global::System.Drawing.Size)(this["BBFormSize"]));
            }
            set {
                this["BBFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Point BBFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["BBFormLocation"]));
            }
            set {
                this["BBFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Point BBSmallFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["BBSmallFormLocation"]));
            }
            set {
                this["BBSmallFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Point UnitRelsaseFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UnitRelsaseFormLocation"]));
            }
            set {
                this["UnitRelsaseFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Size UnitReleaseFromSize {
            get {
                return ((global::System.Drawing.Size)(this["UnitReleaseFromSize"]));
            }
            set {
                this["UnitReleaseFromSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagVisibility {
            get {
                return ((bool)(this["TagVisibility"]));
            }
            set {
                this["TagVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewName {
            get {
                return ((bool)(this["ViewName"]));
            }
            set {
                this["ViewName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CombinePDF {
            get {
                return ((bool)(this["CombinePDF"]));
            }
            set {
                this["CombinePDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoZoom {
            get {
                return ((bool)(this["AutoZoom"]));
            }
            set {
                this["AutoZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100, -100")]
        public global::System.Drawing.Point CWFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["CWFormLocation"]));
            }
            set {
                this["CWFormLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fastener::plan::Fastener||fastener::::DoNotSchedule||component::::Component||extrusion::mod::Extrusion||extrusion::::DoNotSchedule")]
        public string CollectDiesBucketRules {
            get {
                return ((string)(this["CollectDiesBucketRules"]));
            }
            set {
                this["CollectDiesBucketRules"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CollectDiesSelectedSheetSets {
            get {
                return ((string)(this["CollectDiesSelectedSheetSets"]));
            }
            set {
                this["CollectDiesSelectedSheetSets"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CollectDiesSelectedPhases {
            get {
                return ((string)(this["CollectDiesSelectedPhases"]));
            }
            set {
                this["CollectDiesSelectedPhases"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollectDiesCollectAll {
            get {
                return ((bool)(this["CollectDiesCollectAll"]));
            }
            set {
                this["CollectDiesCollectAll"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollectDiesCollectAllViewTypes {
            get {
                return ((bool)(this["CollectDiesCollectAllViewTypes"]));
            }
            set {
                this["CollectDiesCollectAllViewTypes"] = value;
            }
        }
    }
}
